# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distributarepo < Formula
  desc "Helper to get an overview of the forks of a GitHub repository"
  homepage "https://github.com/ldez/distributarepo"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldez/distributarepo/releases/download/v0.4.0/distributarepo_v0.4.0_darwin_amd64.tar.gz"
      sha256 "508eb323df52ffb1983e61e5efb2e7a4cc1c27244e90f9f5f1958b596a523f5e"

      def install
        bin.install "distributarepo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldez/distributarepo/releases/download/v0.4.0/distributarepo_v0.4.0_darwin_arm64.tar.gz"
      sha256 "a912c2449050a5c77f46a2e6f84fe996d73d0d2c4fda5969284937f44da5b1d7"

      def install
        bin.install "distributarepo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.4.0/distributarepo_v0.4.0_linux_amd64.tar.gz"
        sha256 "d0e13551622442e46410464f667dac15aa1ac493f1cc4f4d6fe9ae539f7058dc"

        def install
          bin.install "distributarepo"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.4.0/distributarepo_v0.4.0_linux_armv6.tar.gz"
        sha256 "504a73927d5f4c1196616919439c82c3d87854c26077ff8d63117f2dd6812d0f"

        def install
          bin.install "distributarepo"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.4.0/distributarepo_v0.4.0_linux_arm64.tar.gz"
        sha256 "02d35458d2f389a20b51612dc5e2e306390c5434f7e39f53f8f55107dad0ff88"

        def install
          bin.install "distributarepo"
        end
      end
    end
  end

  test do
    system "#{bin}/distributarepo -v"
  end
end
