# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distributarepo < Formula
  desc "Helper to get an overview of the forks of a GitHub repository"
  homepage "https://github.com/ldez/distributarepo"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/ldez/distributarepo/releases/download/v0.1.1/distributarepo_v0.1.1_darwin_amd64.tar.gz"
      sha256 "99359b03dd66a46dc13c8be6e458849dd962af4526b443340a537804a04f1bbb"

      def install
        bin.install "distributarepo"
      end
    end
    on_arm do
      url "https://github.com/ldez/distributarepo/releases/download/v0.1.1/distributarepo_v0.1.1_darwin_arm64.tar.gz"
      sha256 "368c4ad310592b75f4c0fbfe2492a70fcad3e67f43d23651464e00f80925a3ff"

      def install
        bin.install "distributarepo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.1.1/distributarepo_v0.1.1_linux_amd64.tar.gz"
        sha256 "0e7b13892167cd12c712fac462e29eaeb7614af3bf1188a13570963785d17dd4"

        def install
          bin.install "distributarepo"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.1.1/distributarepo_v0.1.1_linux_armv6.tar.gz"
        sha256 "81f2147e0d04880675ac202dea2b0b991d99a95d1709d2a05c1e81f2e06f73e3"

        def install
          bin.install "distributarepo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/distributarepo/releases/download/v0.1.1/distributarepo_v0.1.1_linux_arm64.tar.gz"
        sha256 "96c200902410a354f069caaca42e2ef108669ff5094c9cbd8bf48ae228701dbc"

        def install
          bin.install "distributarepo"
        end
      end
    end
  end

  test do
    system "#{bin}/distributarepo -v"
  end
end
