# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcg < Formula
  desc "GitHub Changelog Generator"
  homepage "https://github.com/ldez/gcg"
  version "1.7.10"

  on_macos do
    on_intel do
      url "https://github.com/ldez/gcg/releases/download/v1.7.10/gcg_v1.7.10_darwin_amd64.tar.gz"
      sha256 "cf5a334e57c42cbb1dd90b8648b90dfdab3b28269e50e64a134d6f14b1dd849e"

      def install
        bin.install "gcg"
      end
    end
    on_arm do
      url "https://github.com/ldez/gcg/releases/download/v1.7.10/gcg_v1.7.10_darwin_arm64.tar.gz"
      sha256 "0ddc7c50912da42701be5861072d09ad93e40631ae824cc872944d6515fca565"

      def install
        bin.install "gcg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/gcg/releases/download/v1.7.10/gcg_v1.7.10_linux_amd64.tar.gz"
        sha256 "3ef182aae65386ec12a7b90878e3f1152f93add7a1eef972d5f3ced9b3f23109"

        def install
          bin.install "gcg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/gcg/releases/download/v1.7.10/gcg_v1.7.10_linux_arm64.tar.gz"
        sha256 "d63cb6a403a662802a791703bf6cbbcc7905f686b9ab5845487813bd3aa1b0b3"

        def install
          bin.install "gcg"
        end
      end
    end
  end

  test do
    system "#{bin}/gcg version"
  end
end
