# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gcg < Formula
  desc "GitHub Changelog Generator"
  homepage "https://github.com/ldez/gcg"
  version "1.7.9"

  on_macos do
    on_intel do
      url "https://github.com/ldez/gcg/releases/download/v1.7.9/gcg_v1.7.9_darwin_amd64.tar.gz"
      sha256 "34dbaf62b3a7c1d2cff785d020cf0abcf36e60867924fe97f8fb9e0c5e7331ee"

      def install
        bin.install "gcg"
      end
    end
    on_arm do
      url "https://github.com/ldez/gcg/releases/download/v1.7.9/gcg_v1.7.9_darwin_arm64.tar.gz"
      sha256 "8eaef520772ad799646f5f23d6b1300886780e12e40d4a8308e98b398746ba6d"

      def install
        bin.install "gcg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/gcg/releases/download/v1.7.9/gcg_v1.7.9_linux_amd64.tar.gz"
        sha256 "9c19c7250d32da52dab2e45a5873f8084fe3c22e90e4d52fbcb18c36025c5452"

        def install
          bin.install "gcg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/gcg/releases/download/v1.7.9/gcg_v1.7.9_linux_arm64.tar.gz"
        sha256 "3bce07486093cd1a2d640c1cb95334722e5df5c4a6c30086ed0bd8d202d56f05"

        def install
          bin.install "gcg"
        end
      end
    end
  end

  test do
    system "#{bin}/gcg version"
  end
end
