# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Motoko < Formula
  desc "Based on Go modules, update a dependency to a major version"
  homepage "https://github.com/ldez/motoko"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldez/motoko/releases/download/v0.3.2/motoko_v0.3.2_darwin_amd64.tar.gz"
      sha256 "dc63797cd04349e7333400f011a10848ef459e4bf300afa1550df960c578ebef"

      def install
        bin.install "motoko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldez/motoko/releases/download/v0.3.2/motoko_v0.3.2_darwin_arm64.tar.gz"
      sha256 "87caba7a378be14d342f38a383e94e7df463548505ee3febd747e2423b743b78"

      def install
        bin.install "motoko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/motoko/releases/download/v0.3.2/motoko_v0.3.2_linux_amd64.tar.gz"
        sha256 "7eb990e08d66b6fd15329a0c469f5aec452046f02d65ab915747ae244ed785b4"

        def install
          bin.install "motoko"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/motoko/releases/download/v0.3.2/motoko_v0.3.2_linux_armv6.tar.gz"
        sha256 "739b69b77ac8fc49f071997822d747264c74cfd16cacfbb0eaf4e6ebe11e496f"

        def install
          bin.install "motoko"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/motoko/releases/download/v0.3.2/motoko_v0.3.2_linux_arm64.tar.gz"
        sha256 "3c8408a42fcbe80e84b348547a0916dee489e5f9a03ca762855babe391e489ca"

        def install
          bin.install "motoko"
        end
      end
    end
  end

  test do
    system "#{bin}/motoko version"
  end
end
