# This file was generated by GoReleaser. DO NOT EDIT.
class Prm < Formula
  desc "Pull Request Manager for Maintainers"
  homepage "https://github.com/ldez/prm"
  version "3.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ldez/prm/releases/download/v3.1.0/prm_v3.1.0_darwin_amd64.tar.gz"
    sha256 "b1b9a3343ffdbe7111776371ebffcfc533d8517f1f8c827b8e0f24898f96da40"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ldez/prm/releases/download/v3.1.0/prm_v3.1.0_linux_amd64.tar.gz"
      sha256 "3b9c108de3b0a08c57069135709ca0bb74f0dad4a80737841fc4e9ff25e16b47"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/prm/releases/download/v3.1.0/prm_v3.1.0_linux_arm64.tar.gz"
        sha256 "64918934de72a0d9542574b34e933c6420d36b2c5a810549fccaac4e103bb244"
      else
      end
    end
  end

  def install
    bin.install "prm"
  end

  test do
    system "#{bin}/prm --version"
  end
end
