# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prm < Formula
  desc "Pull Request Manager for Maintainers"
  homepage "https://github.com/ldez/prm"
  version "3.6.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldez/prm/releases/download/v3.6.3/prm_v3.6.3_darwin_amd64.tar.gz"
      sha256 "e5ab78e81546880a998fd61840cb0c18ef5a1b1459dcd62e06788d7d457c8957"

      def install
        bin.install "prm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldez/prm/releases/download/v3.6.3/prm_v3.6.3_darwin_arm64.tar.gz"
      sha256 "4cf8f380e08ba5ede60157530fa892fc278fb15a1c5bfe1f639a1c923c494d91"

      def install
        bin.install "prm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/prm/releases/download/v3.6.3/prm_v3.6.3_linux_amd64.tar.gz"
        sha256 "b97f764ff519f2830cd3d8ebdf7a3438e2883c42b9a655257a8ae0a9ee4189c1"

        def install
          bin.install "prm"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ldez/prm/releases/download/v3.6.3/prm_v3.6.3_linux_arm64.tar.gz"
        sha256 "4843baf3b84ba5f01e767eb162888e028812cdad13e34a496f941f415ba8a642"

        def install
          bin.install "prm"
        end
      end
    end
  end

  test do
    system "#{bin}/prm version"
  end
end
