# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seihon < Formula
  desc "Simple tool to publish multi-arch images on the Docker Hub"
  homepage "https://github.com/ldez/seihon"
  version "0.8.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ldez/seihon/releases/download/v0.8.4/seihon_v0.8.4_darwin_amd64.tar.gz"
      sha256 "fd4893a36ad56422476819d52e8f5dcf1eb921ad3505a4db39edfcc46266aa13"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ldez/seihon/releases/download/v0.8.4/seihon_v0.8.4_darwin_arm64.tar.gz"
      sha256 "e183bac1d18aaf7f0fccd58b26d1b0fac62c556bf2efd0445b0e8acea4b68462"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ldez/seihon/releases/download/v0.8.4/seihon_v0.8.4_linux_amd64.tar.gz"
      sha256 "272b82cb8640406b4a4553f8ad795a6fea55dac605bd5ac44af8bd3af2ba5d26"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ldez/seihon/releases/download/v0.8.4/seihon_v0.8.4_linux_arm64.tar.gz"
      sha256 "3cd9ee8b944da5d71f899db4c2b09173da1f594d2b8997b5f0ce92cbb6da8ccf"
    end
  end

  def install
    bin.install "seihon"
  end

  test do
    system "#{bin}/seihon version"
  end
end
